---
language: ruby
ruby:
- "2.2.0"
env:
  matrix:
  - secure: "GpokGY9Vql4ehCwlhGmBOekWY7sxXJkKrJqv9j66An/ZfNiA1j2MewcGNbVFsSwdpYBLSB5ycXvJl+9nNfARfC8mhlkER91RkVeuhEcZDN57N6kuLOzff0HeuV80KXnJUeL5ch/Yq+7GJrNt/JNDxM6txzh5V5QvE1A4viaHqkJEEya8pVlGXAsNWzsetMTh10TeaMGqwALEbG5pDw9pwrNah2ttQ+reE7gjwZGoOeh0AlJaHcB6kGTAt/OI0W6w3EBFcR9EEP2w7UQdUE5yNnO0ab5s4X2ogr+aj7XXPyOrXIwOoPFGVo7A6v90rwzav74W8Ad+Z7SsVeqixFpj62+jaYm84H6Vs4lwMKcsULIg6itL8USAbdzCmmccGB8oSXtaFTdSfU9ACw/532Mm/2MyNxbT0SVpHIPclXHvLIMlcYPKdnhm2iREJu/2snyMmo/kuy07xzMCPkbX6DeT0uJsWNF1UQbuGpHmaI5VSy6yVU2Zh0oWgcwzh/CRqkaBTPRmdTTpTy6rFkg75AgwWhhijbhjTtZkbyCn419Jj/4I+HvlLQqLaJBSj+ElO2n8pOFWY8FeW1Pf8rGyKXebCKRl2qFp45jplFiPp70hJ9W/my/fBQIFz7HEgD4bxy24xDRRO0nMJdwC9ckDVG2ctgRI541Xs1jKwC5OEyu7TzM="
  - secure: "H7HuS3EB2icI+/nHTWar8gnAKs8vARhNPc2eisPk5J1xOyNkZg54F28iWkM1OqmZ6GmtVDCQ2ru10RJGFJ5zOVzpEj9cG3BP66oEUhHQ/n5wAf8T+iHrWGawRNgWAk8e2e40QcEQMkBQ8CLYITmNdrxtDMjhGRfb7+OOtnuG3nIjYXMvDM0Tuawir/ArxoWnFJi/4KRdqxw5pryIQqZtLHLag7bhusrNlVCDFh8WUPfL4WlPfx5LeO2QrtAPsBwNIaeot/9/McisnEEAA8364xinnyxLDJ51b3M/iqvF41AthS4pDyaP1VtK3vcW1XZYEq4xJslGT3yw33SQb921au4qWMjJKma/Wmjh1aVpaS0Che6siMUGwsjg4cc5D4FhzAytCITxkuV/wtOG18udfm5keWMnMTghI4+3Ni5MqmPg6U1BjSOV7I0+sV3Cl8QZFxaUflU1yjJJrHFClH978RcUWTSGYoK8M7TmpD6iHaQm0CMSz8LWB0vwicGdL74ewz38nO6IxgmXfoMyHLOVsn8UZXV6ERR8JW8Jzuh3RprfgchLZWfb1e14ENu70/36rTm/E5iA6PR59Zdluswkb71pHZsHF2vVYaBNbpO5mN4vjfHyz0e3d5cNt62fO0ge98+C7fjNPWC4w0dFtty+QKXndt8tWsMq5lc/WprW2ts="
install:
- gem install bundler
- git clone https://github.com/deconst/preparer-jekyll.git /tmp/preparer-jekyll
- cd /tmp/preparer-jekyll
- rake install
- cd ${TRAVIS_BUILD_DIR}
script:
- deconst-preparer-jekyll
