language: ruby
rvm:
- 2.2.0
env:
  matrix:
  - secure: UQyOHiKozjLJ7oyZWPsRUw/lXV11juPXmD9RPTzhUmt4pVfMGj8/SedUtFBss636EOIR0TdYsDfznusz1/7vGYzhSHzp+lPVLt/6tBlBfvBFWwryd736MUDXTRypJdavt1ShXtrTiEhgkevFGr+Xuw5GdNW93TfhKaYGX7lmLjINqpZCHZt+UDGyghxw79+kyIFHCAJ6NSHWJB9tE2hfGg0Kp9HRarurnIKvrpC/gxispP+Zm2ObOWGDss9khHLNv5gFj2i+5kL9GGl7ojt17AT4wq8cBdlPYJIbIkjxztHfVODtFxiCWg2o+kJ+kmf+c1sJpyB9HpudmM0He6r/cIBc4963pSldOQpiR3Z8fq05zlxcMsJ6ZVMIWfUz+rmjKMfCzAOEXiR3Scdl8P0yzJnO7QWkqtVLNuulZA6OoERhCPWCP8rLJSfgAxVjnvWCm7xTP8ZLwgv6kapbKqmI7gBsACURO2NcmCWyfLEW+ERLKCODwn9r7me9saJp78IiReYJX+63UxUue1hk9UbpUc3gp7zzPwX67cA0PY1Rus5X0aZsbn+NLu8ZL7cwKxvQ+OS5v83JSYf5mN+Z1XSzIREsbvFVawHp6RvxYvKudqsvdgLMm0qRRthpXZtsa8CTO9q4OYFvN62vqLWLCLoIhZBda/VOGKWo5wos9J/o6WA=
  - secure: TCGat1GIb97HtE0cxK6P9aPfv3WpN1vLXLmTkJUPz4pDh9qTZY0eScJTXD9c9dw/M3fuKEPlmhIgsXzyghifk6UbsTaDAfiaj7fj4kuVRpApmNlOZLgQp3qB6HS0qUAmGsaY1fCC5QStvtJARIUFfh/3XvzoqPsH3A7+vzxyLGAjVpeBV6jyoGtq/5gKcIP+tfG5e8QS6r8TILIQX3LdyHipCeRNLzKUYe/P605902kg7Ir1UI2GgSbcldQ74qf/yhA/ARn9DxsAKVPbpsKeyFExKOaJ86lXwtzlaQLgxS51IN0SWPlCpHTlVZRtxhLfwW8a/BYL/vGikMc0SkMETsFlZd5U6rx+76xc5qxMy9M0aBVcIs1P75A4YKpq08eSQ39gTR0e8tYhC10s3lt76R1RCd+7FPoCA/yIso+kktX4ocb29+BdssA7VKAREJxS/WcDBCNwZFs5+zNImzDf5yerDOd3DRPVS10QiZ74MBfR4vzWmtI2MemB68eCXgbWxCv+nSkmQ/HiGEvtC7Z6PMGykcvqPq7XEzwt9MZFPlj7sRxF5wChooVVar7QIjuCmiRY3yL358RjwbFWpzr5mm3fox+UaA/PLcsA2URyrhObEo/iceL2UDGyed46FzHC+ehGGmlDjQUSFeo0UOoP2qBENRFgTGOW6mkImFWBDUM=
install:
- gem env
- git clone https://github.com/deconst/preparer-jekyll.git /tmp/preparer-jekyll
- cd /tmp/preparer-jekyll
- rake build
- gem install /tmp/preparer-jekyll/pkg/preparermd-0.1.0.gem
- cd ${TRAVIS_BUILD_DIR}
script:
- 'echo "Submitting content: ${DESC:-nowhere}"'
- echo ${PATH}
- echo ${GEM_HOME}
- deconst-preparer-jekyll
notifications:
  slack:
    secure: CRE5ZQ0w8Joqp9sFwatVYh8z/r9qEKP4HiSo9V4NKUpJ6xiRe/jMeSicyr28mlQpaT9vhjUPpTDVf4NJpj20pI3vENEqjJElnqbB/OhHCRSO7oDLer9oWRy2+V2SdQIvhAqbb69ai9Wrj2XhkGnVpcc8BwChdSM3/cim8AfqhoKe+TvxfuX34VHmb5ytnH5j0Yg68Bjh9afYBaWb8qgosEHilvXTFqD2Ub29Uu8wVslM5FSeqGfDy49HxMlbN8rS926QEOyhDPtXoWHN/25M5sfQB3Ql7V3DIwZRJYgC5bQ/JpcFaJ3mAJK7bY3vT03SeSSOfDOQmEz2lTTCxdmIY1ajb6aSJcPg8v8IzmhYdy7tuBe/tVmDa7jWqUfhWXEvfHy2Chc6v6dNO0els5RZqOPRo+cc5HoLCD0PMy9zvqUofj31qRkCnfRFvsTbRAbg0vh9NWObXtZYKEQ1VnHbLCWNpVwm6S5jalokaK69bmO1Z2hHPrI969fB9eP7XKTmi0b5C7bbRTQeDwwVpFJzieNeXCwIGYxFutFpqBMJaWvfrLxWV3u1O7jDvs7yL10v47Ie6Cpb++UZ/gJUNxQ/ZmUeTV7RE1V6SZJAqCWbQX00UKAkQy601oJkuuj5gHCe9wX6Zltm4s54GYL2niQFRCjyiFDhl6AdkvDKkxz4fMU=
