---
language: ruby
ruby:
- "2.2.0"
env:
  matrix:
  # Production
  - secure: "iLu5tvG7V/I32xI3F6l8KQLM9iVK5YHNXX69u4o0CgTi8839Q/3PgiVWE+IJ0bzmB8t4QpiSpLhUMOp+A7tgWmAJC8XMqo5YvGhehKfiv+G7zeJxeE5ur8vzROewae/N662waR/w5u+P9Oyrx3IUQ45opeXklh2qry3BucykVfAo+SJ8bgaHASUJQX8OAN1srfKx+243fKi7GhUb3dNZl89SP9g9nrehmjm7LM+wcBaK0TvVliYy/LGeKUmvVXXmXy4U8n51xJXS52/GnQqnMX/S4LhKZzKhMFL+PZbLvkR7CglRp677KUhZC5sL0pnSHvegCB+9TDbYOJuYkHcB+q59anIvZvMU9zmEAv7O2dTt0d8B+6Oj5XhuAtmWNNjAQt2ONJNiZ4D7pCa7IwB5KwzaFPfOI3P+R1JT3rzzfi+yjRpt3HeOO86wGV/Yj0c+q+o9QPgidg9g1LPLFQWZoV5Pwx1qQ+6izq6aaX6ahnc6pZKblrPp3Xyss5Ln+8ERj0o+GtU50tOGbvLAii8kSNhxIty+Gt/51qwtA+jcR3jiKdroNDR/pUBf2zwhEXWXX9/Si+NUOmqHcxdNJEcQX4sReOuuqHfId+h92qV9LX8oNdTz53Im5AGJWrvDsIIPWqEYA9k2iUXfHBE+4dPMUEFVOW0rRuqZL+BSvnsdoWc="
  # Staging
  - secure: "Sn9jHiSrlvTGw0KsAXB5+KNrG8B0s5xxELHpO/p5AW6ee09qGTdPYGkoNjZWw+XdgALFjlCLiIFykUFGqK1Qvo1pDSoI2OMTWkr3S4CiDRyE/4c1cX7a8Ultwp7TnN4Kup+D2R/9Y5ugbmvrG+30U5wMe4rOtn3GmoGUWZBTzvoms6C+mINC9jjQhZL5GS9or/VR/OZFTUS9UHICAl2cLzfrivZu4bxqnyHRoD/rE3UyEJ4kPE0Tx91iuhqmUKS62S83PgG+aKGIPelmlXCAVNUira4ncMKDUjGI8bTUgfUjEIHyq6Y4QPPO6ML20TA7xPY00por/MYMWubMwsPSZLY3O08ixNPdvRNYgGXMqGwDntnIOsAL/B2a2X2Sdg+ti6XOOzEpf1BS7CPXPys0ZbA0uc56WwBRidQnMjrEyYsDiF3W1xSqSmZ9/tmTdqY8AHWJagsCXpPyz6s0VXZA4tFhPCw3gc66mlGSkALZli3SLKko8p3uj2p0j1vGStmWlEP2Mrol68w6mB6c6Qf2yIJ+5kKDSRdNBFoWCJys3JJcQ10tqnpTDTXM/Ss2UuxgAzEyYk+YTRVJP27xPcICa0j2GcDt4QKzqHDVmzYM7lfujsaExKS03rc+13Xf15N+dwofYOdV76AyuKgtomDkw3xLQyu98REsxfmDw95Njb8="
install:
- gem install bundler
- git clone https://github.com/deconst/preparer-jekyll.git /tmp/preparer-jekyll
- cd /tmp/preparer-jekyll
- rake install
- cd ${TRAVIS_BUILD_DIR}
script:
- 'echo "Submitting content: ${DESC:-nowhere}"'
- deconst-preparer-jekyll
