---
language: ruby
ruby:
- "2.2.0"
install:
- gem install bundler
- git clone https://github.com/deconst/preparer-jekyll.git /tmp/preparer-jekyll
- pushd /tmp/preparer-jekyll && bundle install && bundle exec rake install && popd
script:
- deconst-preparer-jekyll
