---
language: ruby
ruby:
- "2.2.0"
install:
- gem install bundler
- git clone https://github.com/deconst/preparer-jekyll.git /tmp/preparer-jekyll
- cd /tmp/preparer-jekyll
- rake install
- cd ${TRAVIS_BUILD_DIR}
script:
- deconst-preparer-jekyll
